import os
import json
import subprocess
from google.auth import default
from google.auth.impersonated_credentials import Credentials as ImpersonatedCredentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload
import io
import vertexai
from vertexai.generative_models import GenerativeModel, Part

from src.common.utils import get_dhash, is_similar

# Configuration
FOLDER_ID = "YOUR_DRIVE_FOLDER_ID"
SERVICE_ACCOUNT_EMAIL = "your-service-account@YOUR_GCP_PROJECT_ID.iam.gserviceaccount.com"
OUTPUT_DIR = "output"
LIBRARY_PATH = os.path.join(OUTPUT_DIR, "post_library.jsonl")
PLAN_MD_OUTPUT = os.path.join(OUTPUT_DIR, "WEEKLY_CONTENT_PLAN.md")
PLAN_JSON_OUTPUT = os.path.join(OUTPUT_DIR, "WEEKLY_CONTENT_PLAN.json")

GCP_PROJECT_ID = "YOUR_GCP_PROJECT_ID"
GCP_LOCATION = "us-central1"

def get_drive_service():
    base_credentials, _ = default()
    scopes = ["https://www.googleapis.com/auth/drive.readonly"]
    if hasattr(base_credentials, 'with_scopes'):
        base_credentials = base_credentials.with_scopes(scopes)
    return build('drive', 'v3', credentials=base_credentials)

def load_posted_hashes():
    posted_hashes = []
    if os.path.exists(LIBRARY_PATH):
        with open(LIBRARY_PATH, 'r') as f:
            for line in f:
                if line.strip():
                    data = json.loads(line)
                    if "image_hash" in data and data["image_hash"]:
                        posted_hashes.append(data["image_hash"])
    return posted_hashes

def read_agent_context():
    """Reads the artifacts generated by Agent 1 and Agent 2."""
    context = {}
    
    digest_path = os.path.join(OUTPUT_DIR, "WEEKLY_DIGEST.md")
    if os.path.exists(digest_path):
        with open(digest_path, "r") as f:
            context["weekly_digest"] = f.read()
    else:
        context["weekly_digest"] = "No weekly digest found."
        
    guide_path = os.path.join(OUTPUT_DIR, "BRAND_INSPIRATION_GUIDE.md")
    if os.path.exists(guide_path):
        with open(guide_path, "r") as f:
            context["style_guide"] = f.read()
    else:
        context["style_guide"] = "No brand style guide found."
        
    hypotheses_path = os.path.join(OUTPUT_DIR, "hypotheses.json")
    if os.path.exists(hypotheses_path):
        with open(hypotheses_path, "r") as f:
            context["hypotheses"] = f.read()
    else:
        context["hypotheses"] = "No hypotheses found."
        
    return context

def convert_heic_to_jpg(heic_path):
    """Converts HEIC to JPG using macOS built-in sips tool."""
    jpg_path = heic_path.replace(".HEIC", ".jpg").replace(".heic", ".jpg")
    try:
        subprocess.run(["sips", "-s", "format", "jpeg", heic_path, "--out", jpg_path], check=True, capture_output=True)
        return jpg_path
    except Exception as e:
        print(f"Error converting {heic_path}: {e}")
        return heic_path

def download_drive_file(service, file_id, file_name):
    request = service.files().get_media(fileId=file_id)
    file_path = os.path.join(OUTPUT_DIR, file_name)
    with io.FileIO(file_path, 'wb') as fh:
        downloader = MediaIoBaseDownload(fh, request)
        done = False
        while done is False:
            status, done = downloader.next_chunk()
    return file_path

def generate_strategic_plan(unposted_files, context):
    """Uses Gemini to evaluate all images against the context and build a 7-day plan."""
    if not unposted_files:
        return {"error": "No new unposted images found."}
        
    try:
        vertexai.init(project=GCP_PROJECT_ID, location=GCP_LOCATION)
        # Using Gemini 3.8 Flash as requested
        model = GenerativeModel("gemini-2.5-flash")
        
        import datetime
        today = datetime.date.today()
        month = today.month
        if month in [12, 1, 2]: season = "Winter"
        elif month in [3, 4, 5]: season = "Spring"
        elif month in [6, 7, 8]: season = "Summer"
        else: season = "Fall/Autumn"

        prompt = f'''You are an elite luxury social media strategist and content planner for an Instagram brand featuring an Irish Setter in a Victorian Country House aesthetic.
        
CRITICAL TEMPORAL & CONTEXTUAL AWARENESS:
Today's date is {today.strftime('%Y-%m-%d')} (Current Season: {season}).
You are acting as a real human posting in real-time. You MUST rigorously evaluate the visual context of every photo to ensure it makes logical sense to post TODAY.
You MUST EXCLUDE any photos from your selection that violate these contextual rules:
1. WEATHER: Do not select photos containing snow unless it is Winter. California allows for sunny photos year-round, but freezing environments/snow storms in {season} are strictly forbidden.
2. HOLIDAYS: Do not select photos with explicit holiday markers (Turkeys/Thanksgiving, Pumpkins/Halloween, Christmas Trees, ornaments, wrapping paper, Easter eggs) unless today's date is within 3 weeks of that holiday.
3. FOLIAGE & NATURE: Match the nature to the season. No bright orange autumn leaves in Spring. No bare, dead winter trees in Summer.
4. ATTIRE: If humans are visible, do not post them wearing heavy snow parkas or winter gear during warm months.

You must generate a 14-Post Content Plan (2 posts per day: Morning and Evening for the next week).'''

Here is your strategic context:
--- AGENT 1: BRAND STYLE GUIDE ---
{context['style_guide']}

--- AGENT 1: WEEKLY TRENDS & AUDIO DIGEST ---
{context['weekly_digest']}

--- AGENT 2: INTERNAL PERFORMANCE HYPOTHESES (What works best for this account) ---
{context['hypotheses']}
--------------------------------------------------

I am providing you with {len(unposted_files)} raw, unposted images from the camera roll.
Your task:
1. Evaluate all the provided images against the Brand Style Guide and the Internal Performance Hypotheses.
2. Select the BEST images to post this week and map them to 14 slots (Morning and Evening for each day). **CRITICAL: Ensure strict visual diversity from slot to slot.** Do NOT place visually similar images (e.g., from the exact same photoshoot, same background, or same angle) on consecutive slots to maintain a fresh, diverse grid.
3. For each slot, YOU MUST decide on the BEST Post Format (e.g., 'carousel', 'single_post', 'reel') designed specifically to MAXIMIZE USER ENGAGEMENT. You must choose the format by cross-referencing:
    - What is currently trending in the Agent 1 Weekly Digest (e.g., if the Digest recommends a 'Reel' or 'Carousel' for a specific aesthetic).
    - What historically yields the highest view/save/share rate for this account based on the Agent 2 Hypotheses (look specifically for 'artifact_type' tag rankings).
4. If choosing 'carousel', select 2-5 related images for that slot.
5. Write a captivating caption. You MUST keep the caption EXTREMELY short—strictly ONE concise sentence. No paragraphs, no extra fluff. Just a single, punchy, human sentence. **CRITICAL: Avoid cheesy, repetitive, or robotic phrases. NEVER use the phrase "My Baby Leo". Write like a highly diverse, natural, modern human creator.**
6. Select a recommended audio track based on the Weekly Digest.

Return your response as a strictly valid JSON object matching this schema:
{{
  "days": [
    {{
      "day_of_week": "Monday - Morning",
      "post_type": "single_post, carousel, or reel",
      "selected_filenames": ["List the exact filenames of the image(s) you selected for this post (e.g. ['IMG_1234.jpg'])"],
      "strategic_rationale": "Why you picked these image(s) and this format based on Agent 1 & Agent 2 data.",
      "caption": "The written caption text.",
      "hashtags": ["#tag1", "#tag2"],
      "recommended_audio": "Audio track idea based on Agent 1 digest"
    }}
  ]
}}
"""
        
        contents = [prompt]
        
        # Load all images into the prompt
        for file_info in unposted_files:
            file_path = file_info["local_path"]
            with open(file_path, "rb") as f:
                image_bytes = f.read()
            # Let Gemini know which file this is by adding text before it
            contents.append(f"Filename: {file_info['name']}")
            contents.append(Part.from_data(mime_type="image/jpeg", data=image_bytes))
            
        models_to_try = [
            "gemini-2.5-pro", 
            "gemini-2.5-flash"
        ]
        
        last_error = None
        for model_name in models_to_try:
            print(f"🤖 Attempting to generate plan using {model_name}...")
            try:
                model = GenerativeModel(model_name)
                response = model.generate_content(
                    contents,
                    generation_config={
                        "temperature": 0.2,
                        "response_mime_type": "application/json"
                    }
                )
                return json.loads(response.text)
            except Exception as e:
                print(f"⚠️ {model_name} failed: {e}")
                last_error = str(e)
                
        return {"error": f"All models failed. Last error: {last_error}"}
        
    except Exception as e:
        print(f"Error calling Gemini: {e}")
        return {"error": str(e)}

def write_markdown_plan(plan_json):
    """Converts the JSON plan into a nice Markdown file."""
    if "error" in plan_json:
        with open(PLAN_MD_OUTPUT, "w") as f:
            f.write(f"# Error Generating Plan\n\n{plan_json['error']}")
        return
        
    days = plan_json.get("days", [])
    
    md = "# 🗓 7-Day Strategic Content Plan\n\n"
    md += "> Generated by Agent #3 based on Agent 1 & 2 Intelligence.\n\n---\n\n"
    
    for day in days:
        md += f"## {day.get('day_of_week', 'Day')} - {str(day.get('post_type', 'single_post')).upper()}\n"
        
        filenames = day.get('selected_filenames', [])
        if isinstance(filenames, str):
            filenames = [filenames] # safety fallback
            
        md += f"* **Selected Asset(s):** " + ", ".join([f"`{f}`" for f in filenames]) + "\n"
        md += f"* **Strategic Rationale:** {day.get('strategic_rationale', '')}\n"
        md += f"* **Audio Track:** {day.get('recommended_audio', '')}\n"
        md += f"\n**Caption:**\n> {day.get('caption', '')}\n\n"
        tags = " ".join(day.get('hashtags', []))
        md += f"**Hashtags:** `{tags}`\n\n---\n\n"
        
    with open(PLAN_MD_OUTPUT, "w") as f:
        f.write(md)
        
    # Archiving Logic
    import datetime
    import re
    archive_path = os.path.join(OUTPUT_DIR, "CONTENT_PLAN_ARCHIVE.md")
    
    # Get current week string, e.g., "Week 38, 2026"
    now = datetime.datetime.now()
    year, week, _ = now.isocalendar()
    week_header = f"# Content Plan: Week {week}, {year}\n"
    
    archive_content = ""
    if os.path.exists(archive_path):
        with open(archive_path, "r") as f:
            archive_content = f.read()
            
    # Check if this week already exists in the archive
    # We will use regex to find the block for this week and replace it, or append to the top
    pattern = rf"(?s)({re.escape(week_header)}.*?)(?=\n# Content Plan: Week|\Z)"
    
    new_block = f"{week_header}\n{md}\n\n"
    
    if re.search(pattern, archive_content):
        # Override the existing week's plan
        archive_content = re.sub(pattern, new_block, archive_content, count=1)
        print(f"🔄 Overwrote existing plan for Week {week}, {year} in archive.")
    else:
        # Append to the top of the archive
        archive_content = f"{new_block}{archive_content}"
        print(f"📥 Added new plan for Week {week}, {year} to archive.")
        
    with open(archive_path, "w") as f:
        f.write(archive_content)

def main():
    print("="*60)
    print("🤖 RUNNING AGENT #3: 7-DAY STRATEGIC CONTENT PLANNER")
    print("="*60)
    
    # 1. Load Context
    print("[1/4] Loading Strategic Context from Agents 1 & 2...")
    context = read_agent_context()
    posted_hashes = load_posted_hashes()
    
    # 2. Fetch Drive Files
    print("[2/4] Connecting to Google Drive...")
    service = get_drive_service()
    query = f"'{FOLDER_ID}' in parents and trashed=false"
    # Limit to 20 for processing time and context window
    results = service.files().list(q=query, pageSize=20, fields="files(id, name, mimeType)").execute()
    items = results.get('files', [])
    
    unposted_files = []
    
    print(f"[3/4] Downloading & Hashing {len(items)} images...")
    for item in items:
        file_path = download_drive_file(service, item['id'], item['name'])
        
        # Convert HEIC if necessary
        is_heic = file_path.lower().endswith(".heic")
        if is_heic:
            file_path = convert_heic_to_jpg(file_path)
            
        current_hash = get_dhash(file_path)
        
        is_duplicate = False
        if current_hash:
            for p_hash in posted_hashes:
                if is_similar(current_hash, p_hash, tolerance=8):
                    is_duplicate = True
                    break
                    
        if is_duplicate:
            print(f"  ⏩ SKIP: {item['name']} (Already posted)")
            os.remove(file_path)
            if is_heic:
                try: os.remove(file_path.replace(".jpg", ".HEIC"))
                except Exception as e: print(f"Warning: could not delete original HEIC: {e}")
        else:
            print(f"  ✅ KEEP: {item['name']} (Fresh)")
            item['local_path'] = file_path
            # We want to send the jpg filename to Gemini so it references it properly
            item['name'] = os.path.basename(file_path)
            unposted_files.append(item)

    # 3. Generate Plan
    print("\n[4/4] Generating Content Plan with Gemini Vision...")
    plan_json = generate_strategic_plan(unposted_files, context)
    
    # Validate filenames
    available_names = {f['name'] for f in unposted_files}
    if "days" in plan_json:
        for day in plan_json["days"]:
            valid_names = []
            for name in day.get("selected_filenames", []):
                # Check direct or without extension
                if name in available_names:
                    valid_names.append(name)
                else:
                    # Attempt fuzzy fix if Gemini dropped extension
                    for an in available_names:
                        if an.startswith(name.split('.')[0]):
                            valid_names.append(an)
                            break
            day["selected_filenames"] = valid_names
    
    with open(PLAN_JSON_OUTPUT, "w") as f:
        json.dump(plan_json, f, indent=2)
        
    write_markdown_plan(plan_json)
    
    # Clean up local files
    for item in unposted_files:
        try:
            os.remove(item['local_path'])
            # cleanup original heic if it exists
            heic_path = item['local_path'].replace(".jpg", ".HEIC").replace(".jpeg", ".heic")
            if os.path.exists(heic_path):
                os.remove(heic_path)
        except:
            pass
            
    print(f"\n🎉 7-Day Content Plan saved to {PLAN_MD_OUTPUT}")
    print(f"💾 Structured data saved to {PLAN_JSON_OUTPUT}")

if __name__ == '__main__':
    main()
