import os
from datetime import datetime

class BrandGuideGenerator:
    """
    Generates structured BRAND_INSPIRATION_GUIDE.md and WEEKLY_DIGEST.md files
    based on analyzed benchmark patterns and weekly trend extractions with direct post URLs.
    """
    def __init__(self, output_dir: str):
        self.output_dir = output_dir

    def generate_weekly_digest(self, weekly_data: dict) -> str:
        os.makedirs(self.output_dir, exist_ok=True)
        digest_path = os.path.join(self.output_dir, "WEEKLY_DIGEST.md")
        
        date_str = datetime.now().strftime("%B %d, %Y")
        
        digest_content = f"""# Social Media Benchmark Weekly Digest
> **Date:** {date_str}  
> **Platforms Analyzed:** Instagram Reels & TikTok  
> **Posts Processed:** {weekly_data['posts_analyzed']} Recent Posts

---

## 1. Fresh Content Ideas & Innovations of the Week

| Handle | Platform | Hook / Concept & Post Link | Audio Track | Views | Key Innovation / Takeaway |
| :--- | :--- | :--- | :--- | :--- | :--- |
"""
        for item in weekly_data['fresh_ideas_of_the_week']:
            link_md = f"[{item['idea']}]({item['post_url']})"
            digest_content += f"| **{item['handle']}** | {item['platform']} | {link_md} | {item['audio']} | `{item['views']}` | {item['innovation']} |\n"

        digest_content += """
---

## 2. Top Emerging Niche Trends This Week

"""
        for trend in weekly_data['emerging_trends']:
            digest_content += f"* **{trend}**\n"

        digest_content += """
---

## 3. Recommended Action Plan for Your Next 7 Days

"""
        for i, action in enumerate(weekly_data.get('action_plan', []), 1):
            parts = action.split(":", 1)
            if len(parts) == 2:
                digest_content += f"{i}. **{parts[0]}:**{parts[1]}\n"
            else:
                digest_content += f"{i}. {action}\n"

        digest_content += """
---
*Generated by Brand Inspiration Weekly Monitoring Agent.*

<br><br>
"""
        # Prepend logic: if file exists, read its contents (skipping the main title if we want, or just prepend)
        existing_content = ""
        if os.path.exists(digest_path):
            with open(digest_path, "r", encoding="utf-8") as f:
                existing_content = f.read()
                
            # If the existing content already has the main title, we might want to just inject below it
            # But the simplest approach is to just keep prepending the whole block (with its own date header)
            # so each week has its own clear section.
            
            # Let's remove the main title from the existing content so we don't have multiple # H1 tags
            if existing_content.startswith("# Social Media Benchmark Weekly Digest\n"):
                existing_content = existing_content.replace("# Social Media Benchmark Weekly Digest\n", "", 1)
                
            digest_content += existing_content

        with open(digest_path, "w", encoding="utf-8") as f:
            f.write(digest_content)

        return digest_path

    def generate_markdown_guide(self, patterns: dict, accounts_list: list) -> str:
        os.makedirs(self.output_dir, exist_ok=True)
        file_path = os.path.join(self.output_dir, "BRAND_INSPIRATION_GUIDE.md")
        
        date_str = datetime.now().strftime("%B %d, %Y")

        md_content = f"""# Brand Inspiration & Style Guidelines Policy Document
> **Brand Concept:** Victorian Country House in Los Angeles with Pets & Slow Living  
> **Product Line:** Heritage-Aesthetic Pet Apparel (Snoods, Dresses, Knits)  
> **Core Lead Characters:** Irish Setters, Cats, Peacocks, Beekeeping & Garden Life

---

## 1. Executive Summary & Brand World
This document serves as the foundational style, content, and aesthetic policy guide for our social media presence. It is distilled from analyzing **{patterns['total_accounts_analyzed']} top benchmark accounts** across pet-anchored lifestyle, cottagecore, and luxury pet apparel spaces on **Instagram and TikTok**.

Our brand promise sells **unhurried, sensory-rich Victorian elegance in sunny California**, where dogs and pets are lead characters in a cozy, slow-living world.

---

## 2. Benchmark Reference Accounts Matrix

| Handle | Platform | Followers | Core Category | Key Takeaway / What to Steal |
| :--- | :--- | :--- | :--- | :--- |
"""
        for acc in accounts_list:
            md_content += f"| **{acc['handle']}** | {acc['platform']} | {acc['followers']} | {acc['category']} | {acc['what_to_steal']} |\n"

        md_content += """
---

## 3. Visual & Aesthetic Standards

### Color Palette & Lighting
* **Lighting:** Warm golden hour sun, moody interior lamp light, soft natural window light.
* **Palette:** Deep forest greens, rich burgundy/rust, antique gold, cream, warm wood tones, and floral prints.
* **Avoid:** Harsh ring lights, fluorescent indoor lighting, or cold blue digital filters.

### Setting & Framing
* **The Historic House:** Frame shots with dark wood trim, wallpapered reading nooks, velvet armchairs, and brass hardware.
* **The Secret LA Garden:** Overgrown flower beds, terra cotta pots, stone archways, and brick pathways where Irish Setters can wander.

---

## 4. Audio & Soundscape Rules

> [!TIP]
> **Sound is 50% of the retention engine.** Our accounts prioritize sensory relaxation over noisy trends.

1. **ASMR Paws & Nature:** Crisp audio of dog paws clicking on Victorian hardwood, crunching dry leaves in the garden, purring, and tea being poured.
2. **Classical & Acoustic Scoring:** Orchestral cello, solo piano, or soft acoustic strings.
3. **Voiceover Policy:** "Present but Partial" — unhurried, warm voiceover paired with hands-in-frame rather than talking-head videos.

---

## 5. High-Retention Content Formulas

"""
        for i, hook in enumerate(patterns['video_hook_formulas'], 1):
            md_content += f"""### Formula {i}: {hook['name']}
* **Structure:** {hook['structure']}
* **Hook Type:** `{hook['hook_type']}`
* **Retention Driver:** {hook['retention_driver']}

"""

        md_content += """---

## 6. Heritage Pet Apparel Integration Rules (Snoods & Dresses)

* **Context First:** Show dog snoods being worn during garden walks (protecting long ears from dirt/burrs) or while eating.
* **Editorial Craftsmanship:** Treat pet clothing like luxury human heritage fashion (close-ups on stitching, natural linen/wool textures).
* **Flat-Lay Styling:** Pair dog snoods/dresses with fresh garden blooms, antique scissors, and tea cups for Pinterest-ready posts.

---

## 7. Voice, Tone & Copywriting Rules

> [!IMPORTANT]
> Captions must sound like they were written by a real, relatable, humble human—not a formal brand or AI. Keep them relatively short and impactful.

* **Core Values:** The voice must radiate a genuine love for animals, a deep appreciation for nature, the beauty of slow living, and an admiration for aesthetics.
* **Tone:** Humble and heartfelt, but with a sprinkle of gentle sarcasm and humor about the realities of living with pets. 
* **No Corporate Speak:** NEVER use words like "We", "Our", or "Us". Write in the first person ("I", "my").
* **Naming:** The Irish Setter's name is **Leo**. Refer to him as Leo, "my baby", "this goofball", etc.

### Caption Example Library (Mimic this exact style and length)
* **Example 1 (Aesthetic + Sarcasm):** "Leo just dragged half the garden into the house, but at least his ears stayed clean in this snood. The glamour of slow living, right?"
* **Example 2 (Nature/Humble):** "Just watching the fog roll in with my favorite boy. Sometimes the simplest, quietest mornings are the ones I cherish the most. 🌲"
* **Example 3 (Animals/Aesthetic):** "Caught the afternoon light perfectly hitting the antique lace... right before the kitten decided it was a climbing wall. Can't even be mad at a face like that."
* **Example 4 (Short/Sweet):** "My baby, Leo, pretending he didn't just try to eat a bee. 🍯 Nothing but love for this beautiful goofball."

---

## 8. Strict Brand Dos & Don'ts

### DO
"""
        for do in patterns['dos_and_donts']['dos']:
            md_content += f"* {do}\n"

        md_content += "\n### DON'T\n"
        for dont in patterns['dos_and_donts']['donts']:
            md_content += f"* {dont}\n"

        # Check for existing Running Log
        existing_log = ""
        log_marker = "## 8. Running Log of New Insights"
        if os.path.exists(file_path):
            with open(file_path, "r", encoding="utf-8") as f:
                content = f.read()
                if log_marker in content:
                    existing_log = content.split(log_marker)[1].split("---")[0].strip()

        md_content += f"""
---

{log_marker}

{existing_log}

### Update: {date_str}
* Validated {patterns['total_accounts_analyzed']} benchmark accounts.
* Confirmed the high retention value of the "Heroic Field & Ridge Shot" (Loki Style) and the "Taste-Test & Garden Forage" (Tucker Style) as key drivers for this week.
"""

        md_content += f"""
---
*Document automatically generated & maintained by the Brand Inspiration Agent.*
"""

        with open(file_path, "w", encoding="utf-8") as f:
            f.write(md_content)

        return file_path
